const express = require("express");
const PDFDocument = require("pdfkit");
const pool = require("../db/pool");
const { authenticate } = require("../middleware/auth");

const router = express.Router();

// GET /reports/procurement-summary/:project_id
router.get("/procurement-summary/:project_id", authenticate, async (req, res) => {
  const { project_id } = req.params;
  try {
    const [project, materials, alerts] = await Promise.all([
      pool.query("SELECT * FROM projects WHERE id = $1", [project_id]),
      pool.query(`
        SELECT m.*, 
          sr.supplier_name as best_supplier,
          sr.unit_price as best_price,
          sr.cortex_score,
          sr.risk_level,
          sr.delivery_days
        FROM materials m
        LEFT JOIN supplier_recommendations sr ON sr.material_id = m.id AND sr.recommended = true
        WHERE m.project_id = $1
      `, [project_id]),
      pool.query("SELECT * FROM risk_alerts WHERE project_id = $1 AND is_read = false ORDER BY severity", [project_id]),
    ]);

    if (!project.rows[0]) return res.status(404).json({ error: "Project not found" });

    const proj = project.rows[0];
    const mats = materials.rows;
    const alts = alerts.rows;

    // Generate PDF
    const doc = new PDFDocument({ margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="procurement-summary-${project_id}.pdf"`);
    doc.pipe(res);

    // Header
    doc.fontSize(24).font("Helvetica-Bold").fillColor("#1a1a2e")
       .text("ARENA ARCHITECT", 50, 50);
    doc.fontSize(12).font("Helvetica").fillColor("#555")
       .text("Material Supply Optimizer — Procurement Summary", 50, 80);

    doc.moveTo(50, 100).lineTo(550, 100).strokeColor("#e63946").lineWidth(2).stroke();

    // Project Info
    doc.fontSize(18).font("Helvetica-Bold").fillColor("#1a1a2e")
       .text(proj.name, 50, 120);
    doc.fontSize(11).font("Helvetica").fillColor("#333")
       .text(`Location: ${proj.location || "N/A"}   |   Status: ${proj.status}   |   Budget: ₹${Number(proj.total_budget || 0).toLocaleString()}`, 50, 145);
    doc.text(`Report Generated: ${new Date().toLocaleDateString("en-IN", { dateStyle: "long" })}`, 50, 162);

    // KPIs
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#e63946").text("KEY METRICS", 50, 195);
    const totalCost = mats.reduce((s, m) => s + (m.best_price || m.estimated_unit_price || 0) * (m.quantity || 0), 0);
    const highRisk = mats.filter(m => m.risk_level === "high").length;

    doc.fontSize(11).font("Helvetica").fillColor("#333");
    doc.text(`• Total Materials: ${mats.length}`, 50, 215);
    doc.text(`• Estimated Total Cost: ₹${totalCost.toLocaleString()}`, 50, 230);
    doc.text(`• High-Risk Materials: ${highRisk}`, 50, 245);
    doc.text(`• Active Alerts: ${alts.length}`, 50, 260);

    // Materials Table
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#e63946").text("MATERIAL RECOMMENDATIONS", 50, 290);
    doc.moveTo(50, 308).lineTo(550, 308).strokeColor("#ccc").lineWidth(1).stroke();

    // Table headers
    doc.fontSize(9).font("Helvetica-Bold").fillColor("#555");
    doc.text("Material", 50, 315);
    doc.text("Qty", 200, 315);
    doc.text("Best Supplier", 240, 315);
    doc.text("Unit Price", 380, 315);
    doc.text("Risk", 460, 315);
    doc.text("Days", 510, 315);

    doc.moveTo(50, 328).lineTo(550, 328).strokeColor("#eee").lineWidth(0.5).stroke();

    let y = 335;
    for (const mat of mats.slice(0, 20)) {
      if (y > 700) { doc.addPage(); y = 50; }
      doc.fontSize(9).font("Helvetica").fillColor("#222");
      doc.text(mat.name.substring(0, 25), 50, y);
      doc.text(`${mat.quantity || 0} ${mat.unit || ""}`, 200, y);
      doc.text(mat.best_supplier ? mat.best_supplier.substring(0, 20) : "Pending", 240, y);
      doc.text(`₹${mat.best_price || mat.estimated_unit_price || 0}`, 380, y);
      doc.text(mat.risk_level || "N/A", 460, y);
      doc.text(mat.delivery_days ? `${mat.delivery_days}d` : "N/A", 510, y);
      y += 18;
    }

    // Alerts section
    if (alts.length > 0) {
      if (y > 650) { doc.addPage(); y = 50; }
      doc.fontSize(14).font("Helvetica-Bold").fillColor("#e63946").text("ACTIVE ALERTS", 50, y + 20);
      y += 45;
      for (const alert of alts.slice(0, 10)) {
        doc.fontSize(10).font("Helvetica").fillColor("#333");
        doc.text(`[${alert.severity.toUpperCase()}] ${alert.message}`, 50, y);
        y += 18;
      }
    }

    // Footer
    doc.fontSize(9).fillColor("#999").text("Generated by Arena Architect — Material Supply Optimizer", 50, 750);
    doc.end();

  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to generate report" });
  }
});

module.exports = router;
